#!/bin/bash
cd ~
if [ -d ~/Scans ]; then
  cd ~/Scans
else
  mkdir ~/Scans
  cd ~/Scans
fi
if [ -d $(date +%Y) ]; then
  cd $(date +%Y)
else
  mkdir $(date +%Y)
  cd $(date +%Y)
fi
if [ -d $(date +%m) ]; then
  cd $(date +%m)
else
  mkdir $(date +%m)
  cd $(date +%m)
fi
if [ -d $(date +%d) ]; then
  cd $(date +%d)
else
  mkdir $(date +%d)
  cd $(date +%d)
fi

ip_addr=$(ifconfig en0 | awk '/inet / {print $2; }')
echo $ip_addr
first_num=$(echo $ip_addr | cut -d '.' -f1)
if [ $first_num -eq "10" ]; then
   sudo nmap -sV -T4 10.*.*.* -oN $(date +%H%M)
elif [ $first_num -eq "172" ]; then
   sudo nmap -sV -T4 172.16.*.* -oN $(date +%H%M)
elif [ $first_num -eq "192" ]; then
   sudo nmap -sV -T4 192.168.*.* -oN $(date +%H%M)
else
   sudo nmap -sV -T4 $first_num.*.*.* -oN $(date +%H%M)
fi

